-- Story Test Lab step definitions.
-- Declares how to prepare environments; does not execute gameplay.

local defs = {
	SCHEMA_VERSION = 1,
	PREREQ = {
		AUTO = "auto",
		MINIMAL = "minimal",
		CUSTOM = "custom",
	},
	ENTRY = {
		STATE_ONLY = "state_only",
		NATURAL = "natural",
		DIRECT = "direct",
		DIRECT_SCENE = "direct_scene",
	},
}

-- Floor aliases for transport (console stage command + StageType).
defs.LEVEL_PRESETS = {
	home_beast = {
		label = {zh = "Home / Beast", en = "Home / Beast"},
		command = "8",
		stage = "STAGE8",
		stage_type = "ORIGINAL",
	},
	downpour_dross_2 = {
		label = {zh = "Downpour / Dross II", en = "Downpour / Dross II"},
		command = "2c",
		stage = "STAGE1_2",
		stage_type = "REPENTANCE",
		route = "alt",
	},
	mines_ashpit = {
		label = {zh = "Mines / Ashpit I", en = "Mines / Ashpit I"},
		command = "3c",
		stage = "STAGE2_1",
		stage_type = "REPENTANCE",
		route = "alt",
	},
	mausoleum_gehenna_1 = {
		label = {zh = "Mausoleum / Gehenna I", en = "Mausoleum / Gehenna I"},
		command = "5c",
		stage = "STAGE3_1",
		stage_type = "REPENTANCE",
		route = "alt",
	},
	mausoleum_gehenna_2 = {
		label = {zh = "Mausoleum / Gehenna II", en = "Mausoleum / Gehenna II"},
		command = "6c",
		stage = "STAGE3_2",
		stage_type = "REPENTANCE",
		route = "alt",
	},
	current = {
		label = {zh = "当前楼层", en = "Current floor"},
		command = nil,
	},
}

-- MATERIAL_ROUTE / MATERIAL_NODES are derived in story_test_registry from story_defs.alchemy.

-- Spine order for auto prerequisites after materials.
defs.SPINE_AFTER_MATERIALS = {
	"chapter1.alchemy_setup",
	"chapter1.enter_realms",
	"chapter1.search_qing",
	"chapter1.qing_midboss",
	"chapter1.post_qing",
	"chapter1.revelation",
	"chapter1.deep_realms",
	"chapter1.glaze_confrontation",
	"chapter1.glaze_boss",
	"chapter1.complete",
}

local function step(t)
	t.repeatable = t.repeatable ~= false
	t.prereq_mode = t.prereq_mode or "auto"
	t.entry = t.entry or {mode = "state_only"}
	t.implementation_status = t.implementation_status or "implemented"
	return t
end

defs.steps = {
	-- Prologue
	step({
		id = "prologue.hunt.state",
		chapter = "prologue",
		group = "prologue",
		label = {zh = "狩猎：状态", en = "Hunt: State"},
		story_node = "prologue.hunt",
		story = {
			status = "active",
			current_node = "prologue.hunt",
			objective = nil,
			completed_nodes = {},
			discovered_nodes = {"prologue.hunt"},
		},
		entry = {mode = "state_only"},
		expected = {
			chapter = "prologue",
			current_node = "prologue.hunt",
		},
		notes = {
			zh = "只设置 hunt active，检查 Quest / Pause UI。",
			en = "State only: hunt active for Quest / Pause UI checks.",
		},
	}),
	step({
		id = "prologue.hunt.opening",
		chapter = "prologue",
		group = "prologue",
		label = {zh = "狩猎：开场", en = "Hunt: Opening"},
		story_node = "prologue.hunt",
		story = {
			status = "locked",
			current_node = nil,
			completed_nodes = {},
			discovered_nodes = {},
		},
		entry = {mode = "direct_scene", scene = "prologue.hunt.opening"},
		expected = {quest_resolves = false},
		expected_after_complete = {
			chapter = "prologue",
			current_node = "prologue.hunt",
		},
		notes = {
			zh = "Prepare=序章前；Trigger=正式开场（章节标题 → 空档 → hunt Toast）。正式运行触发点是 STAGE3_2 + BACKWARDS_PATH_INIT。",
			en = "Prepare=before prologue; Trigger=formal opening (title → gap → hunt toast). Live trigger: STAGE3_2 + BACKWARDS_PATH_INIT.",
		},
	}),
	step({
		id = "prologue.home_arrival",
		chapter = "prologue",
		group = "prologue",
		label = {zh = "抵达 Home", en = "Home Arrival"},
		story_node = "prologue.hunt",
		story = {
			status = "active",
			current_node = "prologue.hunt",
			objective = nil,
			completed_nodes = {},
			discovered_nodes = {"prologue.hunt"},
		},
		entry = {mode = "direct_scene", scene = "prologue.home_arrival"},
		expected = {
			chapter = "prologue",
			current_node = "prologue.hunt",
		},
		expected_after_complete = {
			chapter = "prologue",
			current_node = "prologue.home_encounter",
			node_completed = "prologue.hunt",
		},
		notes = {
			zh = "Prepare=hunt active；Trigger=on_prologue_home_arrived（完成 Toast → 新任务）。",
			en = "Prepare=hunt; Trigger=home arrival (complete toast → new objective).",
		},
	}),
	step({
		id = "prologue.home_encounter",
		chapter = "prologue",
		group = "prologue",
		label = {zh = "Home 相遇", en = "Home Encounter"},
		story_node = "prologue.home_encounter",
		story = {
			status = "active",
			current_node = "prologue.home_encounter",
			objective = nil,
			completed_nodes = {"prologue.hunt"},
			discovered_nodes = {"prologue.hunt", "prologue.home_encounter"},
		},
		entry = {mode = "state_only"},
		expected = {
			chapter = "prologue",
			current_node = "prologue.home_encounter",
			node_completed = "prologue.hunt",
		},
		notes = {
			zh = "可选目标；完成对白→complete；离开卧室→skip 不 complete。",
			en = "Optional; dialogue completes; leaving bedroom skips without complete.",
		},
	}),
	step({
		id = "prologue.home.complete",
		chapter = "prologue",
		group = "prologue",
		label = {zh = "Home：对白结束", en = "Home: Dialogue Done"},
		story_node = "prologue.beast_battle",
		story = {
			status = "active",
			current_node = "prologue.home_encounter",
			completed_nodes = {"prologue.hunt"},
			discovered_nodes = {"prologue.hunt", "prologue.home_encounter"},
		},
		entry = {mode = "direct_scene", scene = "prologue.home.complete"},
		expected_after_complete = {
			chapter = "prologue",
			current_node = "prologue.beast_battle",
			node_completed = "prologue.home_encounter",
			flag = "met_isaac_before_beast",
		},
		notes = {zh = "Trigger=on_prologue_home_encounter_completed", en = "Trigger=home encounter completed"},
	}),
	step({
		id = "prologue.home.skip",
		chapter = "prologue",
		group = "prologue",
		label = {zh = "Home：跳过互动", en = "Home: Skip"},
		story_node = "prologue.beast_battle",
		story = {
			status = "active",
			current_node = "prologue.home_encounter",
			completed_nodes = {"prologue.hunt"},
			discovered_nodes = {"prologue.hunt", "prologue.home_encounter"},
		},
		entry = {mode = "direct_scene", scene = "prologue.home.skip"},
		expected_after_complete = {
			chapter = "prologue",
			current_node = "prologue.beast_battle",
			flag = "home_encounter_skipped",
		},
		notes = {zh = "不 complete home_encounter", en = "Does not complete home_encounter"},
	}),
	step({
		id = "prologue.beast.before",
		chapter = "prologue",
		group = "prologue",
		label = {zh = "追猎阶段", en = "Pursuit Phase"},
		story_node = "prologue.beast_battle",
		story = {
			status = "active",
			current_node = "prologue.beast_battle",
			completed_nodes = {"prologue.hunt"},
			discovered_nodes = {"prologue.hunt", "prologue.home_encounter", "prologue.beast_battle"},
			flags = {home_encounter_skipped = true},
		},
		entry = {mode = "state_only"},
		expected = {
			chapter = "prologue",
			current_node = "prologue.beast_battle",
		},
	}),
	step({
		id = "prologue.ending1_cutscene",
		chapter = "prologue",
		group = "prologue",
		label = {zh = "Ending1 演出", en = "Ending1 Cutscene"},
		story_node = "prologue.ending",
		story = {
			status = "active",
			current_node = "prologue.ending",
			completed_nodes = {
				"prologue.hunt",
				"prologue.beast_battle",
			},
			discovered_nodes = {
				"prologue.hunt",
				"prologue.home_encounter",
				"prologue.beast_battle",
				"prologue.ending",
			},
			flags = {home_encounter_skipped = true},
		},
		entry = {mode = "direct_scene", scene = "prologue.ending"},
		expected = {},
		implementation_status = "partial",
		notes = {
			zh = "Preview: scenes.play_preview(prologue.ending)；正式完成走 on_prologue_ending_complete。",
			en = "Preview via play_preview; formal finish via on_prologue_ending_complete.",
		},
	}),
}

do
	local phase_labels = {
		qing_charges_beast = {zh = "Ending：冲锋", en = "Ending: Charge"},
		beast_fatal_blow = {zh = "Ending：致命一击", en = "Ending: Fatal Blow"},
		qing_reaches_eye = {zh = "Ending：伸手", en = "Ending: Reaches Eye"},
		glaze_seizes_eye = {zh = "Ending：琉璃夺眼", en = "Ending: Glaze Seizes"},
		standoff = {zh = "Ending：对峙", en = "Ending: Standoff"},
		clash = {zh = "Ending：对战", en = "Ending: Clash"},
		qing_protects_isaac = {zh = "Ending：保护以撒", en = "Ending: Qing Protects"},
		aftermath = {zh = "Ending：余波", en = "Ending: Aftermath"},
	}
	local ok, edefs = pcall(require, "Qing_Remaster_scripts.story.prologue.ending_defs")
	local order = (ok and edefs and edefs.PHASE_ORDER) or {}
	for _, phase_id in ipairs(order) do
		local label = phase_labels[phase_id] or {
			zh = "Ending：" .. phase_id,
			en = "Ending: " .. phase_id,
		}
		defs.steps[#defs.steps + 1] = step({
			id = "prologue.ending." .. phase_id,
			chapter = "prologue",
			group = "prologue",
			label = label,
			story_node = "prologue.ending",
			story = {
				status = "active",
				current_node = "prologue.ending",
				completed_nodes = {"prologue.hunt", "prologue.beast_battle"},
				discovered_nodes = {
					"prologue.hunt",
					"prologue.home_encounter",
					"prologue.beast_battle",
					"prologue.ending",
				},
				flags = {home_encounter_skipped = true},
			},
			entry = {mode = "direct_scene", scene = "prologue.ending." .. phase_id},
			expected = {},
			implementation_status = "partial",
			notes = {
				zh = "纯 Preview：不写 StoryProgress / StoryRun / Unlock。",
				en = "Preview only: no StoryProgress / StoryRun / Unlock mutation.",
			},
		})
	end

	-- Art-only BodyPanels preview (0..7). Background stays on Scene MAIN.
	local art_labels = {
		[0] = {zh = "图1 冲锋", en = "Art1 Charge"},
		[1] = {zh = "图2 致命一击", en = "Art2 Fatal Blow"},
		[2] = {zh = "图3 伸手", en = "Art3 Reaches Eye"},
		[3] = {zh = "图4 夺眼", en = "Art4 Seizes Eye"},
		[4] = {zh = "图5 对峙", en = "Art5 Standoff"},
		[5] = {zh = "图6 对战", en = "Art6 Clash"},
		[6] = {zh = "图7 保护", en = "Art7 Protects"},
		[7] = {zh = "图8 余波", en = "Art8 Aftermath"},
	}
	local frame_count = (ok and edefs and edefs.ART_FRAME_COUNT) or 8
	for i = 0, frame_count - 1 do
		local label = art_labels[i] or {
			zh = "Ending 图" .. tostring(i + 1),
			en = "Ending Art " .. tostring(i + 1),
		}
		defs.steps[#defs.steps + 1] = step({
			id = "prologue.ending.art." .. tostring(i),
			chapter = "prologue",
			group = "prologue",
			label = label,
			story_node = "prologue.ending",
			story = {
				status = "active",
				current_node = "prologue.ending",
				completed_nodes = {"prologue.hunt", "prologue.beast_battle"},
				discovered_nodes = {
					"prologue.hunt",
					"prologue.home_encounter",
					"prologue.beast_battle",
					"prologue.ending",
				},
				flags = {home_encounter_skipped = true},
			},
			entry = {mode = "direct_scene", scene = "prologue.ending.art." .. tostring(i)},
			expected = {},
			implementation_status = "partial",
			notes = {
				zh = "仅预览 BodyPanels 分镜；无对白推进。MENUBACK 退出。",
				en = "BodyPanels art preview only; no dialogue. MENUBACK to exit.",
			},
		})
	end
end

-- Remaining chapter1+ steps (kept after prologue phase previews).
local rest_steps = {
	-- Commission
	step({
		id = "chapter1.commission.before",
		chapter = "chapter1",
		group = "commission",
		label = {zh = "委托：之前", en = "Commission: Before"},
		story_node = "chapter1.commission",
		canonical_materials_before = 0,
		story = {
			status = "available",
			current_node = "chapter1.commission",
			objective = "chapter1.accept_commission",
			commission_accepted = false,
			completed_nodes = {},
			tokens = {},
		},
		entry = {mode = "state_only"},
		expected = {
			objective = "chapter1.accept_commission",
			flag_absent = "commission_accepted",
		},
	}),
	step({
		id = "chapter1.commission.scene",
		chapter = "chapter1",
		group = "commission",
		label = {zh = "委托：演出", en = "Commission: Scene"},
		story_node = "chapter1.commission",
		canonical_materials_before = 0,
		story = {
			status = "available",
			current_node = "chapter1.commission",
			objective = "chapter1.accept_commission",
			commission_accepted = false,
		},
		entry = {mode = "direct_scene", scene = "chapter1.commission"},
		implementation_status = "planned",
		expected = {objective = "chapter1.accept_commission"},
	}),
	step({
		id = "chapter1.commission.after",
		chapter = "chapter1",
		group = "commission",
		label = {zh = "委托：之后", en = "Commission: After"},
		story_node = "chapter1.commission",
		canonical_materials_before = 0,
		story = {
			status = "active",
			current_node = "chapter1.material_phase",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			completed_nodes = {"chapter1.commission"},
			tokens = {},
		},
		entry = {mode = "state_only"},
		expected = {
			objective = "chapter1.collect_materials",
			flag = "commission_accepted",
			material_count = 0,
		},
	}),

	-- Coin
	step({
		id = "chapter1.coin.before",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "银行：之前", en = "Coin: Before"},
		story_node = "chapter1.coin",
		canonical_materials_before = 0,
		story = {
			status = "active",
			current_node = "chapter1.material_phase",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			completed_nodes = {"chapter1.commission"},
			tokens = {},
			absent_tokens = {"chapter1.material.coin"},
		},
		level_preset = "current",
		entry = {mode = "natural"},
		thread = {id = "coin", phase = "pre_trigger", reset = true},
		expected = {objective = "chapter1.collect_materials", material_count = 0},
	}),
	step({
		id = "chapter1.coin.discover",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "银行：发现", en = "Coin: Discover"},
		story_node = "chapter1.coin",
		canonical_materials_before = 0,
		story = {
			status = "active",
			current_node = "chapter1.material_phase",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			completed_nodes = {"chapter1.commission"},
			discovered_nodes = {"chapter1.coin"},
			tokens = {},
		},
		entry = {mode = "state_only"},
		expected = {side_event = "chapter1.coin"},
	}),
	step({
		id = "chapter1.coin.boss",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "银行：Boss", en = "Coin: Boss"},
		story_node = "chapter1.coin",
		canonical_materials_before = 0,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			completed_nodes = {"chapter1.commission"},
			discovered_nodes = {"chapter1.coin"},
		},
		entry = {mode = "state_only"},
		thread = {id = "coin", phase = "boss", reset = true},
		expected = {token_absent = "chapter1.material.coin"},
		implementation_status = "partial",
	}),
	step({
		id = "chapter1.coin.complete",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "银行：完成", en = "Coin: Complete"},
		story_node = "chapter1.coin",
		canonical_materials_before = 1,
		force_tokens = {"chapter1.material.coin"},
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			completed_nodes = {"chapter1.commission", "chapter1.coin"},
			tokens = {"chapter1.material.coin"},
		},
		entry = {mode = "state_only"},
		expected = {material_count = 1, token = "chapter1.material.coin"},
	}),
	step({
		id = "chapter1.coin.repeat_acquisition",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "银行：重复取得", en = "Coin: Repeat Acquisition"},
		story_node = "chapter1.coin",
		canonical_materials_before = 0,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			-- Permanent first clear already done; this run lacks the token.
			completed_nodes = {"chapter1.commission", "chapter1.coin"},
			tokens = {},
			absent_tokens = {"chapter1.material.coin"},
		},
		entry = {mode = "state_only"},
		thread = {id = "coin", phase = "repeat_acquisition", reset = true},
		expected = {
			token_absent = "chapter1.material.coin",
			node_completed = "chapter1.coin",
		},
		notes = {
			zh = "验证：永久首通后本局取素材不强制 Bum Emperor。",
			en = "Verify repeat acquisition does not mandate Bum Emperor.",
		},
	}),

	-- Glaze（按机制链路切分的可点击验证点）
	step({
		id = "chapter1.glaze.floor_entry",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "镜界：水层入口", en = "Glaze: Floor Entry"},
		story_node = "chapter1.glaze",
		canonical_materials_before = 1,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "downpour_dross_2",
		entry = {mode = "natural"},
		room = {selector = "starting_room"},
		thread = {id = "glaze", phase = "pre_trigger", reset = true},
		expected = {objective = "chapter1.collect_materials", material_count = 1},
		notes = {
			zh = "确认 Downpour/Dross II、Gate、委托与素材前置。",
			en = "Confirm Downpour/Dross II, gate, commission, and material prereqs.",
		},
	}),
	step({
		id = "chapter1.glaze.white_fire_room",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "镜界：白火房", en = "Glaze: White Fire Room"},
		story_node = "chapter1.glaze",
		canonical_materials_before = 1,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "downpour_dross_2",
		entry = {mode = "natural"},
		room = {
			selector = "glaze_mirror_room",
			dimension = "normal",
			spawn_anchor = "mirror_door",
		},
		thread = {id = "glaze", phase = "pre_trigger", reset = true},
		expected = {objective = "chapter1.collect_materials", material_count = 1},
		notes = {
			zh = "自动定位镜子/白火房（正常世界），检查白火与镜子。",
			en = "Locate mirror/white-fire room in the normal dimension.",
		},
	}),
	step({
		id = "chapter1.glaze.mirror_white_fire",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "镜界：镜像白火", en = "Glaze: Mirror White Fire"},
		story_node = "chapter1.glaze",
		canonical_materials_before = 1,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "downpour_dross_2",
		entry = {mode = "natural"},
		room = {
			selector = "glaze_mirror_room",
			dimension = "mirror",
			spawn_anchor = "white_fire",
		},
		thread = {id = "glaze", phase = "mirror_ready", reset = true},
		expected = {objective = "chapter1.collect_materials", material_count = 1},
		notes = {
			zh = "直接进入对应镜像房，确认白火已琉璃化。",
			en = "Enter the mirror dimension and confirm glazed white fire.",
		},
	}),
	step({
		id = "chapter1.glaze.bomb_interact",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "镜界：琉璃火交互", en = "Glaze: Bomb × White Fire"},
		story_node = "chapter1.glaze",
		canonical_materials_before = 1,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "downpour_dross_2",
		entry = {mode = "natural"},
		room = {
			selector = "glaze_mirror_room",
			dimension = "mirror",
			spawn_anchor = "white_fire",
		},
		player = {bombs = 1},
		thread = {id = "glaze", phase = "bomb_interact", reset = true},
		expected = {objective = "chapter1.collect_materials", material_count = 1},
		notes = {
			zh = "站在镜像白火旁，已给 1 普通炸弹 + 1 琉璃炸弹计数；只需按炸弹键。",
			en = "At mirror white fire with 1 bomb + 1 glaze bomb charge; press bomb only.",
		},
	}),
	step({
		id = "chapter1.glaze.mirror_reward",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "镜界：返回奖励", en = "Glaze: Return Reward"},
		story_node = "chapter1.glaze",
		canonical_materials_before = 1,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "downpour_dross_2",
		entry = {mode = "natural"},
		room = {
			selector = "glaze_mirror_room",
			dimension = "mirror",
			spawn_anchor = "mirror_door",
		},
		thread = {id = "glaze", phase = "mirror_transfer_ready", reset = true},
		expected = {objective = "chapter1.collect_materials", material_count = 1},
		notes = {
			zh = "已登记炸弹过镜；过镜/等待，确认琉璃之残生成。",
			en = "Mirror transfer pre-armed; cross/wait for A Shard of Glaze.",
		},
	}),

	-- Stone
	step({
		id = "chapter1.stone.before",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：之前", en = "Stone: Before"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "mines_ashpit",
		entry = {mode = "natural"},
		thread = {id = "stone", phase = "pre_trigger", reset = true},
		expected = {material_count = 2},
	}),
	step({
		id = "chapter1.stone.layout",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：楼层生成", en = "Stone: Floor Layout"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "mines_ashpit",
		entry = {mode = "natural"},
		thread = {id = "stone", phase = "layout_ready", reset = true},
		expected = {material_count = 2},
		notes = {
			zh = "规划 trigger/route/terminal；棋盘尚未激活。",
			en = "Plans trigger/route/terminal; board not active yet.",
		},
	}),
	step({
		id = "chapter1.stone.trigger",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：巨型黑兵房", en = "Stone: Giant Pawn Room"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.stone"},
		},
		level_preset = "mines_ashpit",
		entry = {mode = "natural"},
		thread = {id = "stone", phase = "layout_ready", reset = true},
		room = {selector = "stone_origin"},
		expected = {side_event = "chapter1.stone"},
	}),
	step({
		id = "chapter1.stone.activate",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：触发后", en = "Stone: After Shatter"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.stone"},
		},
		level_preset = "mines_ashpit",
		entry = {mode = "natural"},
		thread = {id = "stone", phase = "board_active", reset = true},
		room = {selector = "stone_origin"},
		expected = {side_event = "chapter1.stone"},
	}),
	step({
		id = "chapter1.stone.route_mid",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：路线中段", en = "Stone: Route Mid"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.stone"},
		},
		level_preset = "mines_ashpit",
		entry = {mode = "natural"},
		thread = {id = "stone", phase = "board_active", reset = true},
		room = {selector = "stone_route_middle"},
		expected = {side_event = "chapter1.stone"},
	}),
	step({
		id = "chapter1.stone.terminal",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：路线终点门", en = "Stone: Terminal Gate"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.stone"},
		},
		level_preset = "mines_ashpit",
		entry = {mode = "natural"},
		thread = {id = "stone", phase = "board_active", reset = true},
		room = {selector = "stone_terminal"},
		expected = {side_event = "chapter1.stone"},
	}),
	step({
		id = "chapter1.stone.antechamber",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：Boss 前厅", en = "Stone: Antechamber"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.stone"},
		},
		level_preset = "mines_ashpit",
		entry = {mode = "natural"},
		thread = {id = "stone", phase = "board_active", reset = true},
		room = {selector = "stone_antechamber"},
		expected = {side_event = "chapter1.stone"},
	}),
	step({
		id = "chapter1.stone.boss",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：Floraine 房", en = "Stone: Floraine Room"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.stone"},
		},
		level_preset = "mines_ashpit",
		entry = {mode = "natural"},
		thread = {id = "stone", phase = "boss", reset = true},
		room = {selector = "stone_floraine"},
		expected = {token_absent = "chapter1.material.stone"},
		notes = {
			zh = "进入 Floraine 房且 suppress_boss；只验地图/门。",
			en = "Enter Floraine with suppress_boss; map/doors only.",
		},
	}),
	step({
		id = "chapter1.stone.discover",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：发现(状态)", en = "Stone: Discover (state)"},
		story_node = "chapter1.stone",
		canonical_materials_before = 2,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.stone"},
		},
		entry = {mode = "state_only"},
		expected = {side_event = "chapter1.stone"},
	}),
	step({
		id = "chapter1.stone.complete",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "棋盘：完成", en = "Stone: Complete"},
		story_node = "chapter1.stone",
		canonical_materials_before = 3,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			completed_nodes = {"chapter1.commission", "chapter1.coin", "chapter1.glaze", "chapter1.stone"},
		},
		entry = {mode = "state_only"},
		expected = {material_count = 3, token = "chapter1.material.stone"},
	}),

	-- Wind
	step({
		id = "chapter1.wind.before",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "风暴：之前", en = "Wind: Before"},
		story_node = "chapter1.wind",
		canonical_materials_before = 3,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "mausoleum_gehenna_1",
		entry = {mode = "natural"},
		thread = {id = "wind", phase = "pre_trigger", reset = true},
		expected = {material_count = 3, objective = "chapter1.collect_materials"},
	}),
	step({
		id = "chapter1.wind.discover",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "风暴：发现", en = "Wind: Discover"},
		story_node = "chapter1.wind",
		canonical_materials_before = 3,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.wind"},
		},
		level_preset = "mausoleum_gehenna_1",
		entry = {mode = "state_only"},
		expected = {side_event = "chapter1.wind", material_count = 3},
	}),
	step({
		id = "chapter1.wind.boss",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "风暴：Boss", en = "Wind: Boss"},
		story_node = "chapter1.wind",
		canonical_materials_before = 3,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.wind"},
		},
		level_preset = "mausoleum_gehenna_1",
		entry = {mode = "natural"},
		thread = {id = "wind", phase = "boss", reset = true},
		implementation_status = "partial",
		expected = {token_absent = "chapter1.material.wind"},
	}),
	step({
		id = "chapter1.wind.complete",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "风暴：完成", en = "Wind: Complete"},
		story_node = "chapter1.wind",
		canonical_materials_before = 4,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			completed_nodes = {
				"chapter1.commission",
				"chapter1.coin",
				"chapter1.glaze",
				"chapter1.stone",
				"chapter1.wind",
			},
		},
		entry = {mode = "state_only"},
		expected = {material_count = 4, token = "chapter1.material.wind"},
	}),

	-- Phase Anchor
	step({
		id = "chapter1.phase_anchor.before",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "相位锚：之前", en = "Phase Anchor: Before"},
		story_node = "chapter1.phase_anchor",
		canonical_materials_before = 4,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			current_node = "chapter1.material_phase",
		},
		level_preset = "mausoleum_gehenna_2",
		entry = {mode = "natural"},
		implementation_status = "planned",
		expected = {material_count = 4},
	}),
	step({
		id = "chapter1.phase_anchor.room",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "相位锚：校准室", en = "Phase Anchor: Room"},
		story_node = "chapter1.phase_anchor",
		canonical_materials_before = 4,
		story = {
			status = "active",
			objective = "chapter1.collect_materials",
			commission_accepted = true,
			discovered_nodes = {"chapter1.phase_anchor"},
		},
		level_preset = "mausoleum_gehenna_2",
		entry = {mode = "direct"},
		implementation_status = "planned",
		expected = {side_event = "chapter1.phase_anchor"},
	}),
	step({
		id = "chapter1.phase_anchor.complete",
		chapter = "chapter1",
		group = "materials",
		label = {zh = "相位锚：完成", en = "Phase Anchor: Complete"},
		story_node = "chapter1.phase_anchor",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.prepare_alchemy",
			commission_accepted = true,
			current_node = "chapter1.alchemy_setup",
			completed_nodes = {
				"chapter1.commission",
				"chapter1.coin",
				"chapter1.glaze",
				"chapter1.stone",
				"chapter1.wind",
				"chapter1.phase_anchor",
				"chapter1.material_phase",
			},
		},
		entry = {mode = "state_only"},
		implementation_status = "planned",
		expected = {material_count = 5, objective = "chapter1.prepare_alchemy"},
	}),

	-- Alchemy / Realms
	step({
		id = "chapter1.alchemy_setup",
		chapter = "chapter1",
		group = "alchemy",
		label = {zh = "炼成装置", en = "Alchemy Setup"},
		story_node = "chapter1.alchemy_setup",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.prepare_alchemy",
			commission_accepted = true,
			current_node = "chapter1.alchemy_setup",
			completed_nodes = {
				"chapter1.commission",
				"chapter1.material_phase",
			},
		},
		entry = {mode = "direct_scene", scene = "chapter1.alchemy_setup"},
		implementation_status = "planned",
		expected = {objective = "chapter1.prepare_alchemy"},
	}),
	step({
		id = "chapter1.enter_realms",
		chapter = "chapter1",
		group = "alchemy",
		label = {zh = "进入他界", en = "Enter Realms"},
		story_node = "chapter1.enter_realms",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.enter_realms",
			commission_accepted = true,
			current_node = "chapter1.enter_realms",
			completed_nodes = {
				"chapter1.commission",
				"chapter1.material_phase",
				"chapter1.alchemy_setup",
			},
			flags = {materials_complete = true, alchemy_ready = true},
		},
		entry = {mode = "state_only"},
		expected = {objective = "chapter1.enter_realms"},
	}),

	-- Qing arc
	step({
		id = "chapter1.search_qing",
		chapter = "chapter1",
		group = "realms",
		label = {zh = "寻找青", en = "Search Qing"},
		story_node = "chapter1.search_qing",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.find_qing",
			commission_accepted = true,
			current_node = "chapter1.search_qing",
			completed_nodes = {
				"chapter1.commission",
				"chapter1.material_phase",
				"chapter1.alchemy_setup",
				"chapter1.enter_realms",
			},
		},
		entry = {mode = "state_only"},
		expected = {objective = "chapter1.find_qing"},
	}),
	step({
		id = "chapter1.qing_midboss",
		chapter = "chapter1",
		group = "realms",
		label = {zh = "青 Midboss", en = "Qing Midboss"},
		story_node = "chapter1.qing_midboss",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.find_qing",
			commission_accepted = true,
			current_node = "chapter1.qing_midboss",
		},
		entry = {mode = "state_only"},
		implementation_status = "partial",
		expected = {objective = "chapter1.find_qing"},
	}),
	step({
		id = "chapter1.post_qing",
		chapter = "chapter1",
		group = "realms",
		label = {zh = "青战后", en = "Post Qing"},
		story_node = "chapter1.post_qing",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.find_qing",
			commission_accepted = true,
			current_node = "chapter1.post_qing",
			completed_nodes = {
				"chapter1.qing_midboss",
			},
		},
		entry = {mode = "direct_scene", scene = "chapter1.post_qing"},
		implementation_status = "planned",
		expected = {current_node = "chapter1.post_qing"},
	}),
	step({
		id = "chapter1.revelation",
		chapter = "chapter1",
		group = "realms",
		label = {zh = "真相揭露", en = "Revelation"},
		story_node = "chapter1.revelation",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.find_qing",
			commission_accepted = true,
			current_node = "chapter1.revelation",
			completed_nodes = {
				"chapter1.qing_midboss",
				"chapter1.post_qing",
			},
			truth_revealed = false,
		},
		entry = {mode = "direct_scene", scene = "chapter1.revelation"},
		complete_hook = "on_revelation",
		implementation_status = "partial",
		expected_after_complete = {
			objective = "chapter1.stop_glaze",
			flag = "truth_revealed",
		},
		expected = {current_node = "chapter1.revelation"},
	}),

	-- Endgame
	step({
		id = "chapter1.deep_realms",
		chapter = "chapter1",
		group = "endgame",
		label = {zh = "深入他界", en = "Deep Realms"},
		story_node = "chapter1.deep_realms",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.stop_glaze",
			commission_accepted = true,
			truth_revealed = true,
			current_node = "chapter1.deep_realms",
			completed_nodes = {
				"chapter1.qing_midboss",
				"chapter1.post_qing",
				"chapter1.revelation",
			},
		},
		entry = {mode = "state_only"},
		expected = {objective = "chapter1.stop_glaze", flag = "truth_revealed"},
	}),
	step({
		id = "chapter1.glaze_confrontation",
		chapter = "chapter1",
		group = "endgame",
		label = {zh = "对峙琉璃", en = "Glaze Confrontation"},
		story_node = "chapter1.glaze_confrontation",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.confront_glaze",
			commission_accepted = true,
			truth_revealed = true,
			current_node = "chapter1.glaze_confrontation",
		},
		entry = {mode = "direct_scene", scene = "chapter1.glaze_confrontation"},
		implementation_status = "planned",
		expected = {objective = "chapter1.confront_glaze"},
	}),
	step({
		id = "chapter1.glaze_boss",
		chapter = "chapter1",
		group = "endgame",
		label = {zh = "琉璃王子", en = "Glaze Boss"},
		story_node = "chapter1.glaze_boss",
		canonical_materials_before = 5,
		story = {
			status = "active",
			objective = "chapter1.defeat_glaze",
			commission_accepted = true,
			truth_revealed = true,
			current_node = "chapter1.glaze_boss",
			completed_nodes = {"chapter1.glaze_confrontation"},
		},
		entry = {mode = "boss_glaze"},
		implementation_status = "wip",
		expected = {objective = "chapter1.defeat_glaze"},
	}),
	step({
		id = "chapter1.complete",
		chapter = "chapter1",
		group = "endgame",
		label = {zh = "第一章完成", en = "Chapter 1 Complete"},
		story_node = "chapter1.complete",
		canonical_materials_before = 5,
		story = {
			status = "completed",
			objective = nil,
			commission_accepted = true,
			truth_revealed = true,
			completed_nodes = {"chapter1.glaze_boss", "chapter1.complete"},
		},
		entry = {mode = "state_only"},
		expected = {chapter_status = "completed"},
	}),
}

for _, s in ipairs(rest_steps) do
	defs.steps[#defs.steps + 1] = s
end

return defs
