local enums = {}

enums.Players = {
	wq = Isaac.GetPlayerTypeByName("W.Qing"),
	Spwq = Isaac.GetPlayerTypeByName("SP.W.Qing",true),
	Tecro = Isaac.GetPlayerTypeByName("Tecro"),
	Tecrorun = Isaac.GetPlayerTypeByName("Tecrorun",true),
	Anna = Isaac.GetPlayerTypeByName("Anna"),
	annA = Isaac.GetPlayerTypeByName("annA",true),
	Zeistos = Isaac.GetPlayerTypeByName("Zeistos"),
	Zeiz = Isaac.GetPlayerTypeByName("Zeiz", true),
	Marriano = Isaac.GetPlayerTypeByName("Marriano"),
	Autio = Isaac.GetPlayerTypeByName("Autio"),
	Lu = Isaac.GetPlayerTypeByName("Lu"),
}

enums.Items = {
	Darkness = Isaac.GetItemIdByName("Darkness"),
	Touchstone = Isaac.GetItemIdByName("Touchstone"),
	My_Hat = Isaac.GetItemIdByName("My Hat"),
	Tech_9 = Isaac.GetItemIdByName("Tech 9"),
	Assassin_s_Eye = Isaac.GetItemIdByName("Assassin's Eye"),
	A_Shard_Of_Coin = Isaac.GetItemIdByName("A Shard of Coin"),
	A_Shard_Of_Glaze = Isaac.GetItemIdByName("A Shard of Glaze"),
	A_Shard_Of_Lava = Isaac.GetItemIdByName("A Shard of Lava"),
	A_Shard_Of_Meat = Isaac.GetItemIdByName("A Shard of Meat"),
	A_Shard_Of_Rock = Isaac.GetItemIdByName("A Shard of Rock"),
	Mental_Hypnosis = Isaac.GetItemIdByName("Mental Hypnosis"),
	Gold_Rush = Isaac.GetItemIdByName("Gold Rush"),
	Black_Map = Isaac.GetItemIdByName("Black Map"),
	Air_Flight = Isaac.GetItemIdByName("Air Flight"),
	The_Watcher = Isaac.GetItemIdByName("The Watcher"),
	Giant_Punch = Isaac.GetItemIdByName("Giant Punch"),
	Memory = Isaac.GetItemIdByName("Memory"),
	My_Best_Friend = Isaac.GetItemIdByName("My Best Friend"),
	Super_Bombs = Isaac.GetItemIdByName("Super Bombs"),
	Brimstream = Isaac.GetItemIdByName("Brimstream"),
	Crown_of_the_glaze = Isaac.GetItemIdByName("Crown of the Glaze"),
	Blaststone = Isaac.GetItemIdByName("Blaststone"),
	Little_Duck = Isaac.GetItemIdByName("Little Duck"),
	Alchemy_Pot = Isaac.GetItemIdByName("Alchemy Pot"),
	Air_Terror = Isaac.GetItemIdByName("Air Terror"),
	Glaze_Mushroom = Isaac.GetItemIdByName("Glaze Mushroom"),
	Pageant_Cross_dresser = Isaac.GetItemIdByName("Pageant Cross-dresser"),
	It_s_a_trick = Isaac.GetItemIdByName("It's a trick!!"),
	Tianyi = Isaac.GetItemIdByName("Apocalypse"),
	Colorblindness = Isaac.GetItemIdByName("Colorblindness"),
	Field = Isaac.GetItemIdByName("Field"),
	Suture_Needle = Isaac.GetItemIdByName("Suture Needle"),
	More_Options___ = Isaac.GetItemIdByName("More Options??!"),
	Fate_s_Draw = Isaac.GetItemIdByName("Fate's Draw"),
	My_Emblem = Isaac.GetItemIdByName("My Emblem"),
	Ingestion_to_Night = Isaac.GetItemIdByName("Ingestion to Night"),
	D773 = Isaac.GetItemIdByName("D773"),
	Devil_s_Heart = Isaac.GetItemIdByName("Devil's Heart"),
	DVF = Isaac.GetItemIdByName("D-V-F"),
	Book_of_Future = Isaac.GetItemIdByName("Book of Future"),
	Hyper_Velocity = Isaac.GetItemIdByName("Hyper Velocity"),
	Wavering_Eyes = Isaac.GetItemIdByName("Wavering Eyes"),
	Pendulum_Star = Isaac.GetItemIdByName("Pendulum Star"),
	Book_of_Thoth = Isaac.GetItemIdByName("Book of Thoth"),
	Book_of_The_Law = Isaac.GetItemIdByName("Book of The Law"),
	Book_of_Vision = Isaac.GetItemIdByName("Book of Vision"),
	Book_of_Voice = Isaac.GetItemIdByName("Book of Voice"),
	Aphasia = Isaac.GetItemIdByName("Aphasia"),
	Nazca = Isaac.GetItemIdByName("Nazca"),
	Cloundy = Isaac.GetItemIdByName("Cloundy"),
	Skiel = Isaac.GetItemIdByName("Skiel"),
	Wisel = Isaac.GetItemIdByName("Wisel"),
	Granel = Isaac.GetItemIdByName("Granel"),
	Spectralsword = Isaac.GetItemIdByName("Spectralsword"),
	Squiresaga = Isaac.GetItemIdByName("Squiresaga"),
	Moment = Isaac.GetItemIdByName("Moment"),
	Lofty = Isaac.GetItemIdByName("Lofty"),
	Theseus_s_Sign = Isaac.GetItemIdByName("Theseus's Sign"),
	Heart_Change = Isaac.GetItemIdByName("Heart Change"),
	Cable_Jar = Isaac.GetItemIdByName("Cable Jar"),
	Gospel = Isaac.GetItemIdByName("Gospel"),
	Tiramisu = Isaac.GetItemIdByName("Tiramisu"),
	Live_Broadcast = Isaac.GetItemIdByName("Live Broadcast"),
	Drama_of_sorrow_and_joy = Isaac.GetItemIdByName("Drama of sorrow and joy"),
	Tzolkin = Isaac.GetItemIdByName("Tzolkin"),
	Pareidolia = Isaac.GetItemIdByName("Pareidolia"),
	Tears_of_Pearl = Isaac.GetItemIdByName("Tears of Pearl"),
	D_NAN = Isaac.GetItemIdByName("D NAN"),
	Risemara = Isaac.GetItemIdByName("Risemara"),
	Chiastolite = Isaac.GetItemIdByName("Chiastolite"),
	Annihilation = Isaac.GetItemIdByName("Annihilation"),
	Annihilation_ = Isaac.GetItemIdByName("Annihilation "),
	Calamity = Isaac.GetItemIdByName("Calamity"),
	Shadow_Bottle = Isaac.GetItemIdByName("Shadow Bottle"),
	The_True_Name = Isaac.GetItemIdByName("The True Name"),
	Blue_Print = Isaac.GetItemIdByName("Blue Print"),
	Hypermnesia = Isaac.GetItemIdByName("Hypermnesia"),
	Delicate_Flower = Isaac.GetItemIdByName("Delicate Flower"),
	Tech_14 = Isaac.GetItemIdByName("Tech 14"),
	Seeker_s_Eye = Isaac.GetItemIdByName("Seeker's Eye"),
	Day_Dreamer = Isaac.GetItemIdByName("Day Dreamer"),
	Disequilibrium = Isaac.GetItemIdByName("Disequilibrium"),
	Destruction = Isaac.GetItemIdByName("Deconstruction"),
	Philosopher_s_stone = Isaac.GetItemIdByName("Philosopher's stone"),
	Brilliant = Isaac.GetItemIdByName("Brilliant"),
	Fraternity = Isaac.GetItemIdByName("Fraternity"),
	Ending_Count = Isaac.GetItemIdByName("Ending Count"),
	Cheater_s_Blessing = Isaac.GetItemIdByName("Cheater's Blessing"),
	Dimension_Contact = Isaac.GetItemIdByName("Dimension Contact"),
	World_Arc = Isaac.GetItemIdByName("World Arc"),
	Dyson_Star = Isaac.GetItemIdByName("Dyson Star"),
	Final_Prism = Isaac.GetItemIdByName("Final Prism"),
	Book_of_Rune = Isaac.GetItemIdByName("Book of Rune"),
	Evil_Intervention = Isaac.GetItemIdByName("Evil Intervention"),
	Book_of_How_to_Fly = Isaac.GetItemIdByName("How to Fly"),
	Illumination = Isaac.GetItemIdByName("Illumination"),
	Contemplation = Isaac.GetItemIdByName("Contemplation"),
	Chasm = Isaac.GetItemIdByName("Chasm"),
	Book_of_6_sin = Isaac.GetItemIdByName("Book of 6 sin"),
	Pathetique = Isaac.GetItemIdByName("Pathetique"),
	Dark_Mysticism = Isaac.GetItemIdByName("Dark Mysticism"),
	Fresh_Death = Isaac.GetItemIdByName("Fresh Death"),
	The_Suture_Needle = Isaac.GetItemIdByName("The Suture Needle"),
	Glaze_Mirror = Isaac.GetItemIdByName("Glaze Mirror"),
	Mental_Disorder = Isaac.GetItemIdByName("Mental Disorder"),
	Paranoia = Isaac.GetItemIdByName("Paranoia"),
	Cursed_Mask = Isaac.GetItemIdByName("Cursed Mask"),
	Ritual_Sting = Isaac.GetItemIdByName("Ritual Sting"),
	Nihilistic_Artificial_Eye = Isaac.GetItemIdByName("Nihilistic Artificial Eye"),
	Phantom_Crown = Isaac.GetItemIdByName("Phantom Crown"),
	Blood_Wing = Isaac.GetItemIdByName("Blood Wing"),
	Subera_Light = Isaac.GetItemIdByName("Subera Light"),
	D_Plus = Isaac.GetItemIdByName("D Plus"),
	Shangrila = Isaac.GetItemIdByName("Shangrila"),
	Destiny_Anchor = Isaac.GetItemIdByName("Destiny Anchor"),
	Acrotomophilia = Isaac.GetItemIdByName("Acrotomophilia"),
	Loneliness = Isaac.GetItemIdByName("Loneliness"),
	Core_Brooch = Isaac.GetItemIdByName("Core Brooch"),
	Inspiration = Isaac.GetItemIdByName("Fantastic Inspiration"),
	Hunger_Burger = Isaac.GetItemIdByName("Hunger Burger"),
	Muscae_Volitantes = Isaac.GetItemIdByName("Muscae Volitantes"),
	Charon_s_Sign = Isaac.GetItemIdByName("Charon's Sign"),
	Reserved_Judgment = Isaac.GetItemIdByName("Reserved Judgment"),
	Death_Sentence = Isaac.GetItemIdByName("Death Sentence"),
	Remaster = Isaac.GetItemIdByName("Remaster!"),
	Bloody_Map = Isaac.GetItemIdByName("Bloody Map"),
	Golden_Slot = Isaac.GetItemIdByName("Golden Slot"),
	Procrastination = Isaac.GetItemIdByName("Procrastination"),
	Sacred_Mind_Shield = Isaac.GetItemIdByName("Sacred Mind Shield"),
	Qing_Faceted_Market_Diamond = Isaac.GetItemIdByName("Qing's Faceted Market Diamond"),
	Cup_Cat = Isaac.GetItemIdByName("Cup Cat"),
	Abiogenesis = Isaac.GetItemIdByName("Abiogenesis"),
	The_Voice = Isaac.GetItemIdByName("The Voice"),
	Regenesis = Isaac.GetItemIdByName("Regenesis"),
	Ember = Isaac.GetItemIdByName("Ember"),
	
	Baby_Tecro = Isaac.GetItemIdByName("Baby Tecro"),
	Baby_Anna = Isaac.GetItemIdByName("Baby Anna"),
	Baby_Zeis = Isaac.GetItemIdByName("Baby Zeis"),
	Baby_Marri = Isaac.GetItemIdByName("Baby Marri"),
	Baby_Autio = Isaac.GetItemIdByName("Baby Autio"),
	Baby_Lu = Isaac.GetItemIdByName("Baby Lu"),
	
	Kaitian = Isaac.GetItemIdByName("Kaitian"),
	Multiknife = Isaac.GetItemIdByName("Multiknife"),
	Dragon_Tooth = Isaac.GetItemIdByName("Dragon Tooth"),
	
	-- Zeis D-line parked until rewrite (content/items.xml commented; these resolve to -1).
	DI_III = Isaac.GetItemIdByName("D_IIII"),
	D_Heart = Isaac.GetItemIdByName("D Heart"),
	D_Key = Isaac.GetItemIdByName("D Key"),
	D_Bomb = Isaac.GetItemIdByName("D Bomb"),
	D_RazorBlade = Isaac.GetItemIdByName("D RazorBlade"),
	D_Cross = Isaac.GetItemIdByName("D Cross"),
	D_Lusty = Isaac.GetItemIdByName("D Lusty"),
	D_Flame = Isaac.GetItemIdByName("D Flame"),
	D_Rag = Isaac.GetItemIdByName("D Rag"),
	D_Trinity = Isaac.GetItemIdByName("D Trinity"),
	D_Soul = Isaac.GetItemIdByName("D Soul"),
	D_Sacrificalaltar = Isaac.GetItemIdByName("D Sacrificalaltar"),
	D_Coin = Isaac.GetItemIdByName("D Coin"),
	D_Pointyrib = Isaac.GetItemIdByName("D Pointyrib"),
	Book_of_Dull = Isaac.GetItemIdByName("Book of Dull"),
	D_Pack = Isaac.GetItemIdByName("D Pack"),
	
	Reversal_Film = Isaac.GetItemIdByName("Reversal Film"),
}

enums.Trinkets = {
	Pacification_Mark = Isaac.GetTrinketIdByName("Pacification Mark"),
	Dark_Particle = Isaac.GetTrinketIdByName("Dark Particle"),
	Torn_Emperor = Isaac.GetTrinketIdByName("Torn Emperor"),
	Devil_s_Joke = Isaac.GetTrinketIdByName("Devil's Joke"),
	Torn_Moon_ = Isaac.GetTrinketIdByName("Torn Moon?"),
	Puncture_Symbol = Isaac.GetTrinketIdByName("Puncture Symbol"),
	Hoarding_Symbol = Isaac.GetTrinketIdByName("Hoarding Symbol"),
	Transition_Symbol = Isaac.GetTrinketIdByName("Transition Symbol"),
	Adhesive_Symbol = Isaac.GetTrinketIdByName("Adhesive Symbol"),
	Straining_Symbol = Isaac.GetTrinketIdByName("Straining Symbol"),
	Allocation_Symbol = Isaac.GetTrinketIdByName("Allocation Symbol"),
	Pause_ = Isaac.GetTrinketIdByName("Pause?"),
	Equality_Agreement = Isaac.GetTrinketIdByName("Equality Agreement"),
	Consistent_Expectations = Isaac.GetTrinketIdByName("Consistent Expectations"),
	Bundled_Sale = Isaac.GetTrinketIdByName("Bundled Sale"),
	Broken_Brooch = Isaac.GetTrinketIdByName("Broken Brooch"),
}

enums.Callbacks = {		-- Old misspelled callback names were normalized during the REPENTOGON pass.
	POST_PICKUP_COLLECTIBLE = "POST_PICKUP_COLLECTIBLE",
	POST_GAIN_COLLECTIBLE = "POST_GAIN_COLLECTIBLE",
	POST_LOSE_COLLECTIBLE = "POST_LOSE_COLLECTIBLE",
	POST_CHANGE_COLLECTIBLE = "POST_CHANGE_COLLECTIBLE",
	POST_CHANGE_ALL_COLLECTIBLE = "POST_CHANGE_ALL_COLLECTIBLE",
	POST_PICKUP_TRINKET = "POST_PICKUP_TRINKET",
	POST_GAIN_TRINKET = "POST_GAIN_TRINKET",
	POST_LOSE_TRINKET = "POST_LOSE_TRINKET",
	POST_CHANGE_TRINKET = "POST_CHANGE_TRINKET",
	POST_CHANGE_ALL_TRINKET = "POST_CHANGE_ALL_TRINKET",
	POST_PICKUP_POCKET_ITEM = "POST_PICKUP_POCKET_ITEM",
	POST_CHANGE_POCKET_ITEM = "POST_CHANGE_POCKET_ITEM",
	PRE_GET_TELEPORT = "PRE_GET_TELEPORT",
	POST_CHANGE_BASIC = "POST_CHANGE_BASIC",
	POST_CHANGE_ALL_BASIC = "POST_CHANGE_ALL_BASIC",
	PRE_DESCRIPT_ITEM = "PRE_DESCRIPT_ITEM",
	POST_DESCRIPT_ITEM = "POST_DESCRIPT_ITEM",
	PRE_TELL_FORTUNE = "PRE_TELL_FORTUNE",
	PRE_PRE_NEW_LEVEL = "PRE_PRE_NEW_LEVEL",
	PRE_NEW_LEVEL = "PRE_NEW_LEVEL",
	PRE_NEW_ROOM = "PRE_NEW_ROOM",
	PRE_PRE_GAME_STARTED = "PRE_PRE_GAME_STARTED",
	POST_INHERIT_SAVE = "POST_INHERIT_SAVE",
	POST_CLEAR_SAVE = "POST_CLEAR_SAVE",
	PRE_GAME_STARTED = "PRE_GAME_STARTED",
	POST_PRE_GAME_STARTED = "POST_PRE_GAME_STARTED",
	POST_PLAYER_INIT_OVER = "POST_PLAYER_INIT_OVER",
	POST_SLOT_INIT = "POST_SLOT_INIT",
	POST_SLOT_UPDATE = "POST_SLOT_UPDATE",
	POST_SLOT_COLLISION = "POST_SLOT_COLLISION",
	POST_SLOT_KILL = "POST_SLOT_KILL",
	POST_EVERY_ENTITY_INIT = "POST_EVERY_ENTITY_INIT",
	POST_EVERY_ENTITY_UPDATE = "POST_EVERY_ENTITY_UPDATE",
	MC_EVALUATE_IMITATE_ITEM = "MC_EVALUATE_IMITATE_ITEM",
	POST_REASSIGN_IMITATE_ITEM = "POST_REASSIGN_IMITATE_ITEM",
	PRE_CHECK_PRICE = "PRE_CHECK_PRICE",
	PRE_PLAYER_KILL = "PRE_PLAYER_KILL",
	POST_REWIND = "POST_REWIND",
	PRE_CHECK_ITEMPOOL = "PRE_CHECK_ITEMPOOL",
	PRE_GET_COLLECTIBLE = "PRE_GET_COLLECTIBLE",
	PRE_GET_COLLECTIBLE_FROM_POOL = "PRE_GET_COLLECTIBLE_FROM_POOL",
	PRE_QINGS_KNIFE_COLLISION = "PRE_QINGS_KNIFE_COLLISION",
	PRE_ANNAS_PORTAL_COLLISION = "PRE_ANNAS_PORTAL_COLLISION",
	POST_ANNAS_PORTAL_UPDATE = "POST_ANNAS_PORTAL_UPDATE",
	POST_CHECK_PLAYER_POSITIONOFFSET = "POST_CHECK_PLAYER_POSITIONOFFSET",
	POST_PLAYER_SHIFT = "POST_PLAYER_SHIFT",
	POST_GRID_INIT = "POST_GRID_INIT",
	POST_GRID_UPDATE = "POST_GRID_UPDATE",
	PRE_SLOT_RENDER = "PRE_SLOT_RENDER",
	POST_SLOT_RENDER = "POST_SLOT_RENDER",
	--POST_PICKUP_MORPH = "POST_PICKUP_MORPH",
	POST_LASER_INIT_2_UPDATE = "POST_LASER_INIT_2_UPDATE",
	POST_FIRE_TRIGGER = "POST_FIRE_TRIGGER",
	POST_FIRE_TRIGGER_IN_FRAME = "POST_FIRE_TRIGGER_IN_FRAME",
	POST_TRIGGER_BOMB_EFFECT = "POST_TRIGGER_BOMB_EFFECT",
	PRE_ADD_DULL_POINT = "PRE_ADD_DULL_POINT",
	MC_EVALUATE_DULL_POINT = "MC_EVALUATE_DULL_POINT",
}

enums.Slots = {
	Bard_beggar = {Type = 6,Variant = Isaac.GetEntityVariantByName("Bard Beggar"),},
	Tomorrows_creditor = {Type = 6,Variant = Isaac.GetEntityVariantByName("Tomorrows Creditor"),},
	Rift_beggar = {Type = 6,Variant = Isaac.GetEntityVariantByName("Rift Beggar"),},
	Bloody_Messenger = {Type = 6,Variant = Isaac.GetEntityVariantByName("Bloody Messenger"),},
	Qing_Diamond_Merchant = {Type = 6,Variant = Isaac.GetEntityVariantByName("Qing Diamond Merchant"),},
}

enums.Cards = {
	Glaze_dice_shard = Isaac.GetCardIdByName("Glazed Dice Shard"),
	Qing_s_Soul = Isaac.GetCardIdByName("Qing's Soul"),
	Tecro_s_Soul = Isaac.GetCardIdByName("Tecro's Soul"),
	Anna_s_Soul = Isaac.GetCardIdByName("Anna's Soul"),
	Zeis_s_Soul = Isaac.GetCardIdByName("Zeis's Soul"),
	Round_trip_Rail_Ticket = Isaac.GetCardIdByName("Round trip Rail Ticket"),
	One_way_Rail_Ticket = Isaac.GetCardIdByName("One way Rail Ticket"),
	
	Fool = Isaac.GetCardIdByName("The Fool_"),
	Witch = Isaac.GetCardIdByName("The Witch_"),
	Invoker = Isaac.GetCardIdByName("The Invoker_"),
	Wizard = Isaac.GetCardIdByName("The Wizard_"),
	Priestess = Isaac.GetCardIdByName("The High Priestess_"),
	Empress = Isaac.GetCardIdByName("The Empress_"),
	Emperor = Isaac.GetCardIdByName("The Emperor_"),
	Hierophant = Isaac.GetCardIdByName("The Hierophant_"),
	Lover = Isaac.GetCardIdByName("The Lover_"),
	Chariot = Isaac.GetCardIdByName("The Chariot_"),
	Adjustment = Isaac.GetCardIdByName("Adjustment_"),
	Hermit = Isaac.GetCardIdByName("The Hermit_"),
	Wheel_of_Destiny = Isaac.GetCardIdByName("The Wheel of Destiny_"),
	Lure = Isaac.GetCardIdByName("Lure_"),
	Hanged_Man = Isaac.GetCardIdByName("The Hanged Man_"),
	Faint = Isaac.GetCardIdByName("Faint_"),
	Art = Isaac.GetCardIdByName("Art_"),
	Devil = Isaac.GetCardIdByName("The Devil_"),
	Tower = Isaac.GetCardIdByName("The Tower_"),
	Star = Isaac.GetCardIdByName("The Star_"),
	Moon = Isaac.GetCardIdByName("The Moon_"),
	Sun = Isaac.GetCardIdByName("The Sun_"),
	Aeon = Isaac.GetCardIdByName("The Aeon_"),
	Universe = Isaac.GetCardIdByName("The Universe_"),
	
	Fool_r = Isaac.GetCardIdByName("The Fool r_"),
	Sage_r = Isaac.GetCardIdByName("The Sage r_"),
	Priestess_r = Isaac.GetCardIdByName("The High Priestess r_"),
	Empress_r = Isaac.GetCardIdByName("The Empress r_"),
	Emperor_r = Isaac.GetCardIdByName("The Emperor r_"),
	Hierophant_r = Isaac.GetCardIdByName("The Hierophant r_"),
	Lover_r = Isaac.GetCardIdByName("The Lover r_"),
	Chariot_r = Isaac.GetCardIdByName("The Chariot r_"),
	Adjustment_r = Isaac.GetCardIdByName("Adjustment r_"),
	Hermit_r = Isaac.GetCardIdByName("The Hermit r_"),
	Wheel_of_Destiny_r = Isaac.GetCardIdByName("The Wheel of Destiny r_"),
	Lure_r = Isaac.GetCardIdByName("Lure r_"),
	Hanged_Man_r = Isaac.GetCardIdByName("The Hanged Man r_"),
	Faint_r = Isaac.GetCardIdByName("Faint r_"),
	Death_r = Isaac.GetCardIdByName("Death r_"),
	Corpse_r = Isaac.GetCardIdByName("The Corpse r_"),
	Art_r = Isaac.GetCardIdByName("Art r_"),
	Devil_r = Isaac.GetCardIdByName("The Devil r_"),
	Tower_r = Isaac.GetCardIdByName("The Tower r_"),
	Star_r = Isaac.GetCardIdByName("The Stars r_"),
	Moon_r = Isaac.GetCardIdByName("The Moon r_"),
	Sun_r = Isaac.GetCardIdByName("The Sun r_"),
	Aeon_r = Isaac.GetCardIdByName("The Aeon r_"),
	Universe_r = Isaac.GetCardIdByName("The Universe r_"),
	
	Eclipse = Isaac.GetCardIdByName("The Eclipse"),
	Eclipse_r = Isaac.GetCardIdByName("The Eclipse r"),
	Profound = Isaac.GetCardIdByName("The Profound"),
	Profound_r = Isaac.GetCardIdByName("The Profound r"),
	Sting = Isaac.GetCardIdByName("The Sting"),
	Sting_r = Isaac.GetCardIdByName("The Sting r"),
}

enums.SoundEffect = {
	Machine = Isaac.GetSoundIdByName("Machine"),
	Betray = Isaac.GetSoundIdByName("Betray"),
	Rift = Isaac.GetSoundIdByName("Rift"),
	Railway_Ticket = Isaac.GetSoundIdByName("Railway Ticket"),
	Soul_of_Qing = Isaac.GetSoundIdByName("Soul of Qing"),
	Soul_of_Tecro = Isaac.GetSoundIdByName("Soul of Tecro"),
	Soul_of_Anna = Isaac.GetSoundIdByName("Soul of Anna"),
	Soul_of_Zeis = Isaac.GetSoundIdByName("Soul of Zeis"),
	Adjustment = Isaac.GetSoundIdByName("Adjustment"),
	Art = Isaac.GetSoundIdByName("Art"),
	Faint = Isaac.GetSoundIdByName("Faint"),
	Lure = Isaac.GetSoundIdByName("Lure"),
	The_Aeon = Isaac.GetSoundIdByName("The Aeon"),
	The_Eclipse = Isaac.GetSoundIdByName("The Eclipse"),
	The_Invoker = Isaac.GetSoundIdByName("The Invoker"),
	The_Profound = Isaac.GetSoundIdByName("The Profound"),
	The_Sting = Isaac.GetSoundIdByName("The Sting"),
	The_Universe = Isaac.GetSoundIdByName("The Universe"),
	The_Witch = Isaac.GetSoundIdByName("The Witch"),
	The_Wizard = Isaac.GetSoundIdByName("The Wizard"),
	Adjustment_r = Isaac.GetSoundIdByName("Adjustment r"),
	Art_r = Isaac.GetSoundIdByName("Art r"),
	Faint_r = Isaac.GetSoundIdByName("Faint r"),
	Lure_r = Isaac.GetSoundIdByName("Lure r"),
	The_Aeon_r = Isaac.GetSoundIdByName("The Aeon r"),
	The_Corpse_r = Isaac.GetSoundIdByName("The Corpse r"),
	The_Eclipse_r = Isaac.GetSoundIdByName("The Eclipse r"),
	The_Profound_r = Isaac.GetSoundIdByName("The Profound r"),
	The_Sage_r = Isaac.GetSoundIdByName("The Sage r"),
	The_Sting_r = Isaac.GetSoundIdByName("The Sting r"),
	The_Universe_r = Isaac.GetSoundIdByName("The Universe r"),
	Superholy2 = Isaac.GetSoundIdByName("Superholy2"),
	Misc_Fire = Isaac.GetSoundIdByName("Misc_Fire"),
	Qing_smack = Isaac.GetSoundIdByName("Qing_smack"),
	Qing_gunshoots = Isaac.GetSoundIdByName("Qing_gunshoots"),
	Qing_Hit = Isaac.GetSoundIdByName("Qing_Hit"),
	Qing_alarm = Isaac.GetSoundIdByName("Qing_alarm"),
	dialog_type = Isaac.GetSoundIdByName("dialog_type"),
	Qing_shoot = Isaac.GetSoundIdByName("Qing_shoot"),
	Qing_rocket = Isaac.GetSoundIdByName("Qing_rocket"),
}

enums.Music = {
	Weapon_A = Isaac.GetMusicIdByName("Weapon A"),
	Origin_1 = Isaac.GetMusicIdByName("Origin 1"),
	Light_and_Dark = Isaac.GetMusicIdByName("Light and Dark"),
}

enums.Costumes = {
	SPWQinghair = Isaac.GetCostumeIdByPath("gfx/characters/SPWQingHair.anm2"),
	Qingrobes = Isaac.GetCostumeIdByPath("gfx/characters/Qingrobes.anm2"),
	Devil_s_Heart_Head = Isaac.GetCostumeIdByPath("gfx/characters/Devil_s_Heart_Head.anm2"),
	D_s_H_2 = Isaac.GetCostumeIdByPath("gfx/characters/D_s_H_2.anm2"),
	D_s_H_3 = Isaac.GetCostumeIdByPath("gfx/characters/D_s_H_3.anm2"),
	D_s_H_4 = Isaac.GetCostumeIdByPath("gfx/characters/D_s_H_4.anm2"),
	Heart_Change_1 = Isaac.GetCostumeIdByPath("gfx/characters/angel_and_devil_1.anm2"),
	Heart_Change_2 = Isaac.GetCostumeIdByPath("gfx/characters/angel_and_devil_2.anm2"),
	Heart_Change_3 = Isaac.GetCostumeIdByPath("gfx/characters/angel_and_devil_3.anm2"),
	Heart_Change_4 = Isaac.GetCostumeIdByPath("gfx/characters/angel_and_devil_4.anm2"),
	Despia_1 = Isaac.GetCostumeIdByPath("gfx/characters/Despia_Head_1.anm2"),
	Despia_2 = Isaac.GetCostumeIdByPath("gfx/characters/Despia_Head_2.anm2"),
	Despia_3 = Isaac.GetCostumeIdByPath("gfx/characters/Despia_Head_3.anm2"),
	Tecrohair = Isaac.GetCostumeIdByPath("gfx/characters/Tecro_Head.anm2"),
	Tecroface = Isaac.GetCostumeIdByPath("gfx/characters/Tecro_Face.anm2"),
	Pareidolia_1 = Isaac.GetCostumeIdByPath("gfx/characters/Pareidolia_Head2.anm2"),
	Anna_body = Isaac.GetCostumeIdByPath("gfx/characters/Anna_body.anm2"),
	Anna2_body = Isaac.GetCostumeIdByPath("gfx/characters/Anna2_body.anm2"),
	Anna_Horn = Isaac.GetCostumeIdByPath("gfx/characters/Anna_Horn.anm2"),
	Autio_Hair = Isaac.GetCostumeIdByPath("gfx/characters/Autio_Hair.anm2"),
	Zeistos_Head = Isaac.GetCostumeIdByPath("gfx/characters/Zeistos_Head.anm2"),
	Delicate_Flower_Head = Isaac.GetCostumeIdByPath("gfx/characters/Delicate_Flower_Head.anm2"),
	Tecrorun_body = Isaac.GetCostumeIdByPath("gfx/characters/Tecrorun_body.anm2"),
	Tecrorun_head = Isaac.GetCostumeIdByPath("gfx/characters/Tecrorun_head.anm2"),
}

enums.Familiars = {
	QingsAirs = Isaac.GetEntityVariantByName("QingsAir"),
	Brimstream = Isaac.GetEntityVariantByName("Brimstream"),
	Tiandian = Isaac.GetEntityVariantByName("Tiandian"),
	Emblem = Isaac.GetEntityVariantByName("My Emblem"),
	Air_Terror = Isaac.GetEntityVariantByName("Air Terror"),
	Glaze_Chest_Key = Isaac.GetEntityVariantByName("Glaze Chest Key"),
	Glaze_Chest_Key2 = Isaac.GetEntityVariantByName("Glaze Chest Key2"),
	Star_Pendulum = Isaac.GetEntityVariantByName("Star Pendulum"),
	Nazca = Isaac.GetEntityVariantByName("Nazca"),
	Cloundy = Isaac.GetEntityVariantByName("Cloundy"),
	ChiastoliteNil = Isaac.GetEntityVariantByName("ChiastoliteNil"),
	Fraternity = Isaac.GetEntityVariantByName("Fraternity"),
	Subera_Torch = Isaac.GetEntityVariantByName("Subera Torch"),
	Dyson_Star = Isaac.GetEntityVariantByName("Dyson Star"),
	Baby_Tecro = Isaac.GetEntityVariantByName("Baby Tecro"),
	Baby_Anna = Isaac.GetEntityVariantByName("Baby Anna"),
	Baby_Zeis = Isaac.GetEntityVariantByName("Baby Zeis"),
	Baby_Marri = Isaac.GetEntityVariantByName("Baby Marri"),
	Baby_Autio = Isaac.GetEntityVariantByName("Baby Autio"),
	Baby_Lu = Isaac.GetEntityVariantByName("Baby Lu"),
	Abiogenesis = Isaac.GetEntityVariantByName("Abiogenesis"),
}

enums.Enemies = {
	Prince_Glaze = Isaac.GetEntityVariantByName("Prince Glaze"),
	chess_piece = Isaac.GetEntityVariantByName("Chess Piece"),
	chess_board = Isaac.GetEntityVariantByName("Chess Board"),
	Floraine = Isaac.GetEntityVariantByName("Floraine"),
	Staff_Strike = Isaac.GetEntityVariantByName("staff strike"),
	Zennith = Isaac.GetEntityVariantByName("Zennith"),
	wildwind = Isaac.GetEntityVariantByName("Wildwind"),
	chimella = Isaac.GetEntityVariantByName("chimella"),
	Bum_Emperor = Isaac.GetEntityVariantByName("Bum Emperor"),
	Bum_Guard = Isaac.GetEntityVariantByName("Bum Guard"),
	Bum_spear = Isaac.GetEntityVariantByName("Bum spear"),
	Bum_arrow = Isaac.GetEntityVariantByName("Bum arrow"),
	Autio = Isaac.GetEntityVariantByName("Autio"),
	Zeistos = Isaac.GetEntityVariantByName("Zeistos"),
	ShadowToken = Isaac.GetEntityVariantByName("ShadowToken"),
	RemoverToken = Isaac.GetEntityVariantByName("RemoverToken"),
	DestinyToken = Isaac.GetEntityVariantByName("DestinyToken"),
	ZToken = Isaac.GetEntityVariantByName("ZToken"),
	Boss_Qing = Isaac.GetEntityVariantByName("Boss Qing"),
	QingHelper = Isaac.GetEntityVariantByName("QingHelper"),
	QingHelper2 = Isaac.GetEntityVariantByName("QingHelper2"),
	QingKnife = Isaac.GetEntityVariantByName("QingKnife"),
	Absurd = Isaac.GetEntityVariantByName("Absurd"),
}

enums.Entities = {
	QingsAirs = Isaac.GetEntityVariantByName("QingsAir"),
	MeusLink = Isaac.GetEntityVariantByName("MeusLink"),
	QingsMarks = Isaac.GetEntityVariantByName("QingsMark"),
	StabberKnife = Isaac.GetEntityVariantByName("StabberKnife"),
	MeusSword = Isaac.GetEntityVariantByName("MeusSword"),
	ID_EFFECT_MeusFetus = Isaac.GetEntityVariantByName("MeusFetus"),
	ID_EFFECT_MeusRocket = Isaac.GetEntityVariantByName("MeusRocket"),
	ID_EFFECT_MeusNIL = Isaac.GetEntityVariantByName("MeusNil"),
	Qing_Bar = Isaac.GetEntityVariantByName("Qing Bar"),
	Blaststone = Isaac.GetEntityVariantByName("Blaststone"),
	Brimstream = Isaac.GetEntityVariantByName("Brimstream"),
	little_duck = Isaac.GetEntityVariantByName("littleduck"),
	Tiandian = Isaac.GetEntityVariantByName("Tiandian"),
	trans_field_door = Isaac.GetEntityVariantByName("trans field door"),
	Harmony = Isaac.GetEntityVariantByName("Harmony"),
	Glaze_Chest_Key = Isaac.GetEntityVariantByName("Glaze Chest Key"),
	Glaze_Chest_Key2 = Isaac.GetEntityVariantByName("Glaze Chest Key2"),
	Sleep_on_Bed = Isaac.GetEntityVariantByName("Isaac on bed"),
	Feeding_gift = Isaac.GetEntityVariantByName("Feeding Gift"),
	Tecro_Spear = Isaac.GetEntityVariantByName("Tecro Spear"),
	Tecro_Laser_Spear = Isaac.GetEntityVariantByName("Tecro Laser Spear"),
	Tecro_Needle = Isaac.GetEntityVariantByName("Tecro Needle"),
	Shadollee = Isaac.GetEntityVariantByName("Shadollee"),
	TecroNil = Isaac.GetEntityVariantByName("TecroNil"),
	TecroThisNil = Isaac.GetEntityVariantByName("TecroThisNil"),
	TecroNeedleNil = Isaac.GetEntityVariantByName("TecroNeedleNil"),
	TecroLaserNil = Isaac.GetEntityVariantByName("TecroLaserNil"),
	BackDropNil = Isaac.GetEntityVariantByName("BackDropNil"),
	ShadowNil = Isaac.GetEntityVariantByName("ShadowNil"),
	Remover = Isaac.GetEntityVariantByName("Remover"),
	Shadow_Linker = Isaac.GetEntityVariantByName("Shadow Linker"),
	Lu_s_paper = Isaac.GetEntityVariantByName("Lu's Paper"),
	Calamity_door = Isaac.GetEntityVariantByName("Calamity Door"),
	Calamity_ball = Isaac.GetEntityVariantByName("Calamity Ball"),
	Mimic_Damocles = Isaac.GetEntityVariantByName("Mimic Damocles"),
	Anna_Portal = Isaac.GetEntityVariantByName("Anna Portal"),
	EID_Descriptier = Isaac.GetEntityVariantByName("EID_Descriptier"),
	Tech_14_pointer = Isaac.GetEntityVariantByName("Tech_14_pointer"),
	Anna_Partical = Isaac.GetEntityVariantByName("Anna Partical"),
	Disequilibrium_helper = Isaac.GetEntityVariantByName("Disequilibrium helper"),
	Rift_Beggar_Helper = Isaac.GetEntityVariantByName("Rift Beggar Helper"),
	PlayerNil = Isaac.GetEntityVariantByName("PlayerNil"),
	ZeistosHelper = Isaac.GetEntityVariantByName("ZeistosHelper"),
	ZeistosHelper2 = Isaac.GetEntityVariantByName("ZeistosHelper2"),
	Hyper_Velocity_Track = Isaac.GetEntityVariantByName("Hyper Velocity Track"),
	Chasm_Hanger = Isaac.GetEntityVariantByName("Chasm Hanger"),
	Cursed_Linker = Isaac.GetEntityVariantByName("Cursed Linker"),
	S_Pentagram = Isaac.GetEntityVariantByName("S Pentagram"),
	AnnaMarks = Isaac.GetEntityVariantByName("AnnaMarks"),
	AnnaHelper = Isaac.GetEntityVariantByName("AnnaHelper"),
	Phantom = Isaac.GetEntityVariantByName("HelperPhantom"),
	HornHandHelper = Isaac.GetEntityVariantByName("HornHandHelper"),
	ShangrilaHelper = Isaac.GetEntityVariantByName("ShangrilaHelper"),
	ElementPentagram = Isaac.GetEntityVariantByName("ElementPentagram"),
	ElementCrystal = Isaac.GetEntityVariantByName("ElementCrystal"),
	Muscae_Helper = Isaac.GetEntityVariantByName("Muscae Helper"),
	Glaze_Helper = Isaac.GetEntityVariantByName("Glaze Helper"),
}

enums.Pickups = {
	Glaze_heart = {Variant = Isaac.GetEntityVariantByName("Glaze_heart"),SubType = 2350,wei = 50,heavy = 2,},
	Glaze_heart_half = {Variant = Isaac.GetEntityVariantByName("Glaze_heart_half"),SubType = 2351,wei = 70,heavy = 1,},
	Glaze_key = {Variant = Isaac.GetEntityVariantByName("Glaze_key"),SubType = 2352,wei = 80,heavy = 2,},
	Glaze_bomb = {Variant = Isaac.GetEntityVariantByName("Glaze_bomb"),SubType = 2355,wei = 90,heavy = 2,},
	--Glaze_coin = {Variant = Isaac.GetEntityVariantByName("Glaze_coin"),SubType = 2354,wei = 160,heavy = 1,},
	Glaze_coin = {Variant = 20,SubType = 4,wei = 160,heavy = 1,special_to_turn = function(ent,turnin)
		local own_word = "Glaze_Coin"
		local d = ent:GetData()
		d._Data = d._Data or {}
		d._Data[own_word] = d._Data[own_word] or {}
		if turnin == true then
			d._Data[own_word].is_glaze_coin = true
		else
			d._Data[own_word].is_glaze_coin = nil
		end
		local s = ent:GetSprite()
		s:Load("gfx/Glaze/glaze_coin.anm2",true)
		s:Play("Appear",true)
		return true,own_word
	end,special_to_check = function(ent)
		return ent:GetData()._Data and ent:GetData()._Data["Glaze_Coin"] and ent:GetData()._Data["Glaze_Coin"].is_glaze_coin == true
	end,
	},
	Glaze_grabbag = {Variant = Isaac.GetEntityVariantByName("Glaze_grabbag"),SubType = 2353,wei = 30,heavy = 3,},
	Glaze_battery = {Variant = Isaac.GetEntityVariantByName("Glaze_battery"),SubType = 2356,wei = 40,heavy = 2,},
	Glaze_chest = {Variant = Isaac.GetEntityVariantByName("Glaze_chest"),SubType = 2357,wei = 1,heavy = 8,},
	Glaze_big_poop = {Variant = Isaac.GetEntityVariantByName("Glaze_big_poop"),SubType = 2358,wei = 0,heavy = 1,},
	Glaze_dice_shard = {Variant = 300,SubType = Isaac.GetCardIdByName("Glazed Dice Shard"),wei = 10,heavy = 5,},
	
	Inspiration_helper = {Variant = Isaac.GetEntityVariantByName("Inspiration Helper"),SubType = 2439,wei = 0,heavy = 0,},
	-- SubType 运行时 = 收藏品 ID；此处仅登记 Variant
	Blueprint_Prototype = {Variant = Isaac.GetEntityVariantByName("Blueprint Prototype"), SubType = 0, wei = 0, heavy = 0,},
}

enums.Challenges = {
	Fusion_Destiny = Isaac.GetChallengeIdByName("Fusion Destiny"),
	Fans_Service = Isaac.GetChallengeIdByName("Fans Service"),
	Fake_Image = Isaac.GetChallengeIdByName("Fake Image"),
	Heterothermal_Concentric = Isaac.GetChallengeIdByName("Heterothermal Concentric"),
	Feels_Like_Dead_Ashes = Isaac.GetChallengeIdByName("Feels Like Dead Ashes"),
	Louvre_puzzle = Isaac.GetChallengeIdByName("Louvre Puzzle"),
	Unstable_State = Isaac.GetChallengeIdByName("Unstable State"),
	Invisible = Isaac.GetChallengeIdByName("Invisible"),
	Safe_Driving = Isaac.GetChallengeIdByName("Safe Driving"),
	Cookie_Clicker = Isaac.GetChallengeIdByName("Cookie Clicker"),
	Pointing = Isaac.GetChallengeIdByName("Pointing and Disappointing"),
	Swallow_The_Sun = Isaac.GetChallengeIdByName("Swallow The Sun"),
	Dragon_Flight = Isaac.GetChallengeIdByName("Dragon Flight"),
}

enums.AchievementGraphics = {		--未绘制的成就，以及未设计的成就。
	wq = {
		MomsHeart = "achievement_",
		MegaSatan = "achievement_Darkness",
		Lamb = "achievement_Touchstone",
		BlueBaby = "achievement_Glazed_Cap",
		Hush = "achievement_Tech_9",
		BossRush = "achievement_Assassin_s_Eye",
		Delirium = "achievement_Mental_Hypnosis",
		Isaac = "achievement_Pageant_Cross_Dresser",
		Satan = "achievement_More_Options___",
		Beast = "achievement_Ingestion_to_Night",
		Mother = "achievement_Black_Map",
		GreedMode = "achievement_Gold_Rush",
		Greedier = "achievement_glass_door2",
		Tainted = "achievement_tainted_WQ",
		FullCompletion = "achievement_resistance",
	},
	Spwq = {
		--MegaSatan = "achievement_Air_Terror",
		Lamb = "achievement_Air_Flight",
		BlueBaby = "achievement_The_Watcher",
		Hush = "achievement_Soul_of_WQ",
		BossRush = "achievement_Giant_Punch",
		Delirium = "achievement_Memory",
		Isaac = "achievement_Field",
		Satan = "achievement_Little_Duck",
		Beast = "achievement_My_Best_Friend",		--重新确认。
		Mother = "achievement_Super_Bombs",
		GreedMode = "achievement_Fate_s_Draw",
		Greedier = "achievement_Brimstream",
		--FullCompletion = "achievement_Shooting_Underground",
	},
	glaze = {
		Isaac = "achievement_Glaze_Dice_Shard",
		Maggy = "achievement_Glaze_Heart",
		Cain = "achievement_Glaze_Key",
		Judas = "achievement_Glaze_Champion",
		BlueBaby = "achievement_Glaze_Poop",
		Eve = "achievement_Glaze_Bomb",
		Samson = "achievement_Glaze_Chest",
		Azazel = "achievement_Glaze_Brimstone",
		Lazarus = "achievement_Glaze_Pill",
		Eden = "achievement_Glaze_Grabbag",
		Lost = "achievement_Glaze_Item",
		Lilith = "achievement_Glaze_Machine",
		Keeper = "achievement_Glaze_Coin",
		Apollyon = "achievement_Glaze_Fly",
		Forgotten = "achievement_Glaze_Wing",
		Bethany = "achievement_Glaze_Battery",
		Jacob_and_Esau = "achievement_Glaze_Curse",
		
		Isaac_t = "achievement_Feels_Like_Dead_Ash",
		Maggy_t = "achievement_Fans_Service",
		Cain_t = "achievement_Fusion_Destiny",
		Judas_t = "achievement_Dark_Burier",
		BlueBaby_t = "achievement_Global_Pandemic",
		Eve_t = "achievement_Dissipative_Mode",
		Samson_t = "achievement_Kill_a_thousand",
		Azazel_t = "achievement_",
		Lazarus_t = "achievement_Fake_Image",
		Eden_t = "achievement_Unstable",
		Lost_t = "achievement_Lost_Sleeps_Well",
		Lilith_t = "achievement_",
		Keeper_t = "achievement_Louver_Problem",
		Apollyon_t = "achievement_",
		Forgotten_t = "achievement_Gotta_Kick_Them_All",
		Bethany_t = "achievement_",
		Jacob_and_Esau_t = "achievement_Heterothermal_Concentric",
	},
	others = {
		Ending1 = {
			"achievement_My_Emblem",
			"achievement_My_Hat",
		},
		Ending2 = {},
		Ending3 = {},
		Crush = "achievement_Hyper_Velocity",
		Thoth = "achievement_Book_of_Thoth",
		Future = "achievement_Book_of_Future",
	},
}

local function paramtrans(info,params)
	local ret = {}
	for u,v in pairs(params) do ret[u] = params[info[u] or u] end
	return ret
end

local function put_params(ret,F)
	return F(ret[1],ret[2],ret[3],ret[4],ret[5],ret[6],ret[7],ret[8],ret[9],ret[10])
end

enums.REPENTOGON_CALLBACK_MAP = {}
if REPENTOGON then
enums.REPENTOGON_CALLBACK_MAP = {
	PRE_NEW_ROOM = true,
	POST_SLOT_INIT = true,
	POST_SLOT_UPDATE = true,
	POST_SLOT_COLLISION = true,
	POST_SLOT_KILL = true,
	POST_GRID_INIT = true,
	POST_GRID_UPDATE = true,
	POST_PICKUP_POCKET_ITEM = true,
	PRE_SLOT_RENDER = true,
	POST_SLOT_RENDER = true,
}
end

return enums
