-- Generated by build_release.py for public packages. Absent in the development tree.
-- project_version is a snapshot of core/version.lua, not a second version owner.
-- content_scope is decided here, not by parsing the version string in Lua.
return {
    public = true,
    project_version = "alpha-0.1.0",
    release_channel = "alpha",
    content_scope = {
        story_max_chapter = "prologue",
    },
}
